import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const repoRoot = path.resolve(__dirname, '..');
const nodePackageJsonPath = path.join(repoRoot, 'package.json');
const PACKAGE_NAME = JSON.parse(fs.readFileSync(nodePackageJsonPath, 'utf8')).name;

const inputPath = path.join(__dirname, 'test-full.md');
const docxOutputPath = path.join(__dirname, 'test-full.docx');
const pdfOutputPath = path.join(__dirname, 'test-full.pdf');
const htmlOutputPath = path.join(__dirname, 'test-full.html');
const htmlNoneOutputPath = path.join(__dirname, 'test-full.none.html');
const htmlImgOutputPath = path.join(__dirname, 'test-full.img.html');

async function loadApi() {
  try {
    return await import(PACKAGE_NAME);
  } catch (e) {
    const fallback = path.join(repoRoot, '../dist/index.mjs');
    if (fs.existsSync(fallback)) {
      console.warn(`[test] Failed to import "${PACKAGE_NAME}", falling back to ${fallback}`);
      return await import(pathToFileURL(fallback).href);
    }
    throw e;
  }
}

async function main() {
  const api = await loadApi();
  console.log('[test] imported:', PACKAGE_NAME);
  console.log('[test] exports:', Object.keys(api).sort().join(', '));

  if (!fs.existsSync(inputPath)) {
    fs.writeFileSync(
      inputPath,
      '# md2x API test\n\nThis file is generated by `node/test.mjs`.\n\n- item 1\n- item 2\n',
      'utf8'
    );
    console.log(`[test] created: ${inputPath}`);
  }

  // Test DOCX export
  if (typeof api.markdownFileToDocxFile !== 'function') {
    throw new Error('API is missing markdownFileToDocxFile()');
  }
  console.log(`[test] converting to DOCX: ${inputPath}`);
  await api.markdownFileToDocxFile(inputPath, docxOutputPath, { theme: 'default' });
  console.log(`[test] wrote: ${docxOutputPath}`);

  // Test PDF export
  if (typeof api.markdownFileToPdfFile !== 'function') {
    throw new Error('API is missing markdownFileToPdfFile()');
  }
  console.log(`[test] converting to PDF: ${inputPath}`);
  await api.markdownFileToPdfFile(inputPath, pdfOutputPath, { theme: 'default' });
  console.log(`[test] wrote: ${pdfOutputPath}`);

  // Test HTML export
  if (typeof api.markdownFileToHtmlFile !== 'function') {
    throw new Error('API is missing markdownFileToHtmlFile()');
  }
  console.log(`[test] converting to HTML: ${inputPath}`);
  await api.markdownFileToHtmlFile(inputPath, htmlOutputPath, { theme: 'default' });
  console.log(`[test] wrote: ${htmlOutputPath}`);

  const html = fs.readFileSync(htmlOutputPath, 'utf8');
  if (!html.includes('<!DOCTYPE html>') || !html.includes('id="markdown-content"')) {
    throw new Error('HTML export output does not look like a standalone document');
  }
  if (!html.includes('md2x live diagram renderer (CDN)')) {
    throw new Error('HTML export (diagramMode: img, cdn) should include the CDN renderer bootstrap');
  }
  if (!html.includes('cdn.jsdelivr.net/npm/mermaid')) {
    throw new Error('HTML export (diagramMode: img, cdn) should reference Mermaid CDN script');
  }
  if (!html.includes('cdn.jsdelivr.net/npm/@viz-js/viz') && !html.includes('cdn.jsdelivr.net/npm/viz.js')) {
    throw new Error('HTML export (diagramMode: img, cdn) should reference a Graphviz CDN script');
  }
  if (!html.includes('cdn.jsdelivr.net/npm/vega-embed')) {
    throw new Error('HTML export (diagramMode: img, cdn) should reference Vega-Embed CDN script');
  }
  if (!html.includes('cdn.jsdelivr.net/npm/@antv/infographic')) {
    throw new Error('HTML export (diagramMode: img, cdn) should reference AntV Infographic CDN script');
  }
  if (!html.includes('vega-lite@5') || !html.includes('vega-embed@6')) {
    throw new Error('HTML export (diagramMode: img, cdn) should include Vega-Lite v5 CDN mapping for v5 schema specs');
  }

  // Test HTML export (diagramMode: none)
  console.log(`[test] converting to HTML (diagramMode: none): ${inputPath}`);
  await api.markdownFileToHtmlFile(inputPath, htmlNoneOutputPath, { theme: 'default', diagramMode: 'none' });
  console.log(`[test] wrote: ${htmlNoneOutputPath}`);

  const htmlNone = fs.readFileSync(htmlNoneOutputPath, 'utf8');
  if (!htmlNone.includes('language-mermaid')) {
    throw new Error('HTML export (diagramMode: none) should keep mermaid code blocks');
  }
  if (htmlNone.includes('class="md2x-diagram"')) {
    throw new Error('HTML export (diagramMode: none) should not inject rendered diagram blocks');
  }

  // Test HTML export (diagramMode: img)
  console.log(`[test] converting to HTML (diagramMode: img): ${inputPath}`);
  await api.markdownFileToHtmlFile(inputPath, htmlImgOutputPath, { theme: 'default', diagramMode: 'img' });
  console.log(`[test] wrote: ${htmlImgOutputPath}`);

  console.log('[test] all tests passed!');
}

main().catch((err) => {
  const msg = err instanceof Error ? err.stack || err.message : String(err);
  console.error('[test] failed:', msg);
  console.error('\n[test] If you have not built the CLI yet, run: pnpm node');
  process.exit(1);
});
