import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const repoRoot = path.resolve(__dirname, '..');
const nodePackageJsonPath = path.join(repoRoot, 'package.json');
export const PACKAGE_NAME = JSON.parse(fs.readFileSync(nodePackageJsonPath, 'utf8')).name;

// Test file paths
export const testDir = __dirname;
export const demoDir = path.join(__dirname, 'demo');
export const inputPath = path.join(demoDir, 'test-full.md');
export const docxOutputPath = path.join(demoDir, 'test-full.docx');
export const pdfOutputPath = path.join(demoDir, 'test-full.pdf');
export const htmlOutputPath = path.join(demoDir, 'test-full.html');
export const htmlNoneOutputPath = path.join(demoDir, 'test-full.none.html');
export const htmlImgOutputPath = path.join(demoDir, 'test-full.img.html');

// Front matter test files
export const fmPdfPath = path.join(demoDir, 'test-frontmatter-pdf.md');
export const fmPdfLetterPath = path.join(demoDir, 'test-frontmatter-pdf-letter.md');
export const fmPdfA5Path = path.join(demoDir, 'test-frontmatter-pdf-a5.md');
export const fmPdfCustomPath = path.join(demoDir, 'test-frontmatter-pdf-custom.md');
export const fmHtmlPath = path.join(demoDir, 'test-frontmatter-html.md');
export const fmHtmlFragmentPath = path.join(demoDir, 'test-frontmatter-html-fragment.md');
export const fmHtmlThemePath = path.join(demoDir, 'test-frontmatter-html-theme.md');
export const fmDocxPath = path.join(demoDir, 'test-frontmatter-docx.md');
export const fmDiagramNonePath = path.join(demoDir, 'test-frontmatter-diagram-none.md');
export const fmDiagramImgPath = path.join(demoDir, 'test-frontmatter-diagram-img.md');
export const fmInvalidPath = path.join(demoDir, 'test-frontmatter-invalid.md');
export const fmNonePath = path.join(demoDir, 'test-frontmatter-none.md');
export const fmEmptyPath = path.join(demoDir, 'test-frontmatter-empty.md');

let _api = null;

export async function loadApi() {
  if (_api) return _api;

  try {
    _api = await import(PACKAGE_NAME);
  } catch (e) {
    const fallback = path.join(repoRoot, 'dist/index.js');
    if (fs.existsSync(fallback)) {
      console.warn(`Failed to import "${PACKAGE_NAME}", falling back to ${fallback}`);
      _api = await import(pathToFileURL(fallback).href);
    } else {
      throw e;
    }
  }
  return _api;
}

export function ensureTestFile() {
  if (!fs.existsSync(inputPath)) {
    fs.writeFileSync(
      inputPath,
      '# md2x API test\n\nThis file is generated by `node/test.mjs`.\n\n- item 1\n- item 2\n',
      'utf8'
    );
    console.log(`created: ${inputPath}`);
  }
}
