/**
 * Auto-generated theme data - DO NOT EDIT
 * Generated by build.mjs from src/themes/
 */

export const presets_academic = {
  "id": "academic",
  "name": "学术论文",
  "name_en": "Academic",
  "description": "宋体正文配黑体标题，中文学术规范",
  "description_en": "Song body with Hei headings, Chinese academic standard",
  "author": "Markdown Viewer Extension",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "SimSun"
    },
    "headings": {
      "fontFamily": "SimHei"
    },
    "code": {
      "fontFamily": "Monaco"
    }
  },
  "layoutScheme": "academic",
  "colorScheme": "neutral",
  "tableStyle": "academic",
  "codeTheme": "light-clean"
} as const;

export const presets_business = {
  "id": "business",
  "name": "商务报告",
  "name_en": "Business",
  "description": "Calibri 字体，现代商务风格，层次清晰",
  "description_en": "Calibri font with modern business style and clear hierarchy",
  "author": "Markdown Viewer Extension",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Arial"
    },
    "headings": {},
    "code": {
      "fontFamily": "Monaco"
    }
  },
  "layoutScheme": "document",
  "colorScheme": "neutral",
  "tableStyle": "professional",
  "codeTheme": "business-contrast"
} as const;

export const presets_candy = {
  "id": "candy",
  "name": "糖果甜心",
  "name_en": "Candy",
  "description": "糖果甜心，甜美可爱风格",
  "description_en": "Sweet and adorable candy style",
  "author": "Theme System",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Trebuchet MS"
    },
    "headings": {},
    "code": {
      "fontFamily": "Consolas"
    }
  },
  "layoutScheme": "student",
  "colorScheme": "candy",
  "tableStyle": "zebra",
  "codeTheme": "colorful",
  "diagramStyle": "handDrawn"
} as const;

export const presets_century = {
  "id": "century",
  "name": "演示文稿",
  "name_en": "Presentation",
  "description": "Trebuchet MS 字体，简洁的演示风格，标题突出",
  "description_en": "Trebuchet MS font with clean presentation style, prominent headings",
  "author": "Markdown Viewer Extension",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Century Gothic"
    },
    "headings": {},
    "code": {
      "fontFamily": "Monaco"
    }
  },
  "layoutScheme": "magazine",
  "colorScheme": "cool",
  "tableStyle": "minimal-gray",
  "codeTheme": "cool-modern"
} as const;

export const presets_coral = {
  "id": "coral",
  "name": "珊瑚活力",
  "name_en": "Coral Vibrant",
  "description": "温暖橙粉色系，友好亲和的活力风格",
  "description_en": "Warm coral-pink for friendly and vibrant style",
  "author": "Theme System",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Verdana"
    },
    "headings": {},
    "code": {
      "fontFamily": "Consolas"
    }
  },
  "layoutScheme": "book",
  "colorScheme": "coral",
  "tableStyle": "minimal-gray",
  "codeTheme": "colorful"
} as const;

export const presets_default = {
  "id": "default",
  "name": "标准文档",
  "name_en": "Standard",
  "description": "Times New Roman 字体，适合正式文档和论文",
  "description_en": "Times New Roman font for formal documents and papers",
  "author": "Markdown Viewer Extension",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Times New Roman"
    },
    "headings": {},
    "code": {
      "fontFamily": "Monaco"
    }
  },
  "layoutScheme": "document",
  "colorScheme": "neutral",
  "tableStyle": "grid",
  "codeTheme": "light-clean"
} as const;

export const presets_dinosaur = {
  "id": "dinosaur",
  "name": "恐龙探险",
  "name_en": "Dinosaur",
  "description": "绿橙探险，活力恐龙风格",
  "description_en": "Green-orange adventurous dinosaur style",
  "author": "Theme System",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Arial"
    },
    "headings": {},
    "code": {
      "fontFamily": "Consolas"
    }
  },
  "layoutScheme": "student",
  "colorScheme": "dino",
  "tableStyle": "grid",
  "codeTheme": "colorful",
  "diagramStyle": "handDrawn"
} as const;

export const presets_elegant = {
  "id": "elegant",
  "name": "优雅文艺",
  "name_en": "Elegant Literary",
  "description": "Georgia 字体，优雅的文学风格",
  "description_en": "Georgia font with elegant literary style",
  "author": "Markdown Viewer Extension",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Georgia"
    },
    "headings": {},
    "code": {
      "fontFamily": "Monaco"
    }
  },
  "layoutScheme": "book",
  "colorScheme": "sakura",
  "tableStyle": "borderless",
  "codeTheme": "colorful"
} as const;

export const presets_forest = {
  "id": "forest",
  "name": "森林自然",
  "name_en": "Forest Natural",
  "description": "绿色系，自然环保的森林风格",
  "description_en": "Green for natural and eco-friendly forest style",
  "author": "Theme System",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Verdana"
    },
    "headings": {},
    "code": {
      "fontFamily": "Consolas"
    }
  },
  "layoutScheme": "book",
  "colorScheme": "forest",
  "tableStyle": "minimal-gray",
  "codeTheme": "light-clean"
} as const;

export const presets_garamond = {
  "id": "garamond",
  "name": "长文阅读",
  "name_en": "Long Reading",
  "description": "Georgia 字体，舒适的长文阅读体验",
  "description_en": "Georgia font for comfortable long-form reading",
  "author": "Markdown Viewer Extension",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Garamond"
    },
    "headings": {},
    "code": {
      "fontFamily": "Monaco"
    }
  },
  "layoutScheme": "book",
  "colorScheme": "warm",
  "tableStyle": "borderless",
  "codeTheme": "warm-book"
} as const;

export const presets_garden = {
  "id": "garden",
  "name": "花园清新",
  "name_en": "Garden",
  "description": "粉绿清新，可爱花园风格",
  "description_en": "Pink-green fresh garden style",
  "author": "Theme System",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Verdana"
    },
    "headings": {},
    "code": {
      "fontFamily": "Consolas"
    }
  },
  "layoutScheme": "student",
  "colorScheme": "garden",
  "tableStyle": "minimal-gray",
  "codeTheme": "light-clean",
  "diagramStyle": "handDrawn"
} as const;

export const presets_handwritten = {
  "id": "handwritten",
  "name": "手写风格",
  "name_en": "Handwritten",
  "description": "手写体标题，个人化感觉，适合日记和随笔",
  "description_en": "Handwriting style titles for personal notes and journals",
  "author": "Markdown Viewer Extension",
  "version": "2.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Comic Sans MS"
    },
    "headings": {},
    "code": {
      "fontFamily": "Consolas"
    }
  },
  "layoutScheme": "book",
  "colorScheme": "warm",
  "tableStyle": "borderless",
  "codeTheme": "warm-book",
  "diagramStyle": "handDrawn"
} as const;

export const presets_heiti = {
  "id": "heiti",
  "name": "现代黑体",
  "name_en": "Hei Style",
  "description": "黑体字体，现代简约风格",
  "description_en": "Hei font with modern minimal style",
  "author": "Markdown Viewer Extension",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "SimHei"
    },
    "headings": {},
    "code": {
      "fontFamily": "Monaco"
    }
  },
  "layoutScheme": "document",
  "colorScheme": "neutral",
  "tableStyle": "grid",
  "codeTheme": "light-clean"
} as const;

export const presets_magazine = {
  "id": "magazine",
  "name": "杂志排版",
  "name_en": "Magazine",
  "description": "大标题差异，视觉冲击，适合创意内容展示",
  "description_en": "Large title contrast with visual impact for creative content",
  "author": "Markdown Viewer Extension",
  "version": "2.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Georgia"
    },
    "headings": {
      "fontFamily": "Helvetica Neue"
    },
    "code": {
      "fontFamily": "Monaco"
    }
  },
  "layoutScheme": "magazine",
  "colorScheme": "cool",
  "tableStyle": "minimal-gray",
  "codeTheme": "cool-modern"
} as const;

export const presets_manuscript = {
  "id": "manuscript",
  "name": "手稿风格",
  "name_en": "Manuscript",
  "description": "学术手稿感，适合论文草稿和研究笔记",
  "description_en": "Academic manuscript style for paper drafts and research notes",
  "author": "Markdown Viewer Extension",
  "version": "2.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Palatino Linotype"
    },
    "headings": {},
    "code": {
      "fontFamily": "Consolas"
    }
  },
  "layoutScheme": "academic",
  "colorScheme": "sepia",
  "tableStyle": "borderless",
  "codeTheme": "warm-book"
} as const;

export const presets_minimal = {
  "id": "minimal",
  "name": "极简主义",
  "name_en": "Minimal",
  "description": "系统字体，最简洁的排版风格，专注内容本身",
  "description_en": "System font with minimal styling, focus on content itself",
  "author": "Markdown Viewer Extension",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Arial"
    },
    "headings": {},
    "code": {
      "fontFamily": "Monaco"
    }
  },
  "layoutScheme": "document",
  "colorScheme": "neutral",
  "tableStyle": "borderless",
  "codeTheme": "light-clean"
} as const;

export const presets_mixed = {
  "id": "mixed",
  "name": "中英混排",
  "name_en": "Mixed Languages",
  "description": "宋体正文配 Georgia 标题，中英文混排优化",
  "description_en": "Song body with Georgia headings for mixed content",
  "author": "Markdown Viewer Extension",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "SimSun"
    },
    "headings": {
      "fontFamily": "Georgia"
    },
    "code": {
      "fontFamily": "Monaco"
    }
  },
  "layoutScheme": "book",
  "colorScheme": "warm",
  "tableStyle": "grid",
  "codeTheme": "warm-book"
} as const;

export const presets_newspaper = {
  "id": "newspaper",
  "name": "报纸风格",
  "name_en": "Newspaper",
  "description": "传统新闻排版风格，正式严肃",
  "description_en": "Traditional newspaper typography, formal and serious",
  "author": "Markdown Viewer Extension",
  "version": "2.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Times New Roman"
    },
    "headings": {
      "fontFamily": "Georgia"
    },
    "code": {
      "fontFamily": "Consolas"
    }
  },
  "layoutScheme": "magazine",
  "colorScheme": "sepia",
  "tableStyle": "grid",
  "codeTheme": "warm-book"
} as const;

export const presets_ocean = {
  "id": "ocean",
  "name": "海洋清新",
  "name_en": "Ocean Fresh",
  "description": "蓝绿色系，清爽自然的海洋风格",
  "description_en": "Blue-green for fresh and natural ocean style",
  "author": "Theme System",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Trebuchet MS"
    },
    "headings": {},
    "code": {
      "fontFamily": "Consolas"
    }
  },
  "layoutScheme": "document",
  "colorScheme": "ocean",
  "tableStyle": "minimal-gray",
  "codeTheme": "cool-modern"
} as const;

export const presets_palatino = {
  "id": "palatino",
  "name": "书籍出版",
  "name_en": "Book Publishing",
  "description": "Palatino 字体，优雅的书籍出版风格",
  "description_en": "Palatino font with elegant book publishing style",
  "author": "Markdown Viewer Extension",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Palatino"
    },
    "headings": {},
    "code": {
      "fontFamily": "Monaco"
    }
  },
  "layoutScheme": "book",
  "colorScheme": "sepia",
  "tableStyle": "minimal-gray",
  "codeTheme": "warm-book"
} as const;

export const presets_rainbow = {
  "id": "rainbow",
  "name": "彩虹缤纷",
  "name_en": "Rainbow",
  "description": "多彩标题，活泼童趣的彩虹风格",
  "description_en": "Multi-colored headings for vibrant rainbow style",
  "author": "Theme System",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Arial"
    },
    "headings": {},
    "code": {
      "fontFamily": "Consolas"
    }
  },
  "layoutScheme": "student",
  "colorScheme": "rainbow",
  "tableStyle": "zebra",
  "codeTheme": "colorful",
  "diagramStyle": "handDrawn"
} as const;

export const presets_space = {
  "id": "space",
  "name": "太空探索",
  "name_en": "Space",
  "description": "蓝橙科幻，太空探索风格",
  "description_en": "Blue-orange sci-fi space exploration style",
  "author": "Theme System",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Arial"
    },
    "headings": {},
    "code": {
      "fontFamily": "Consolas"
    }
  },
  "layoutScheme": "student",
  "colorScheme": "space",
  "tableStyle": "modern-tech",
  "codeTheme": "cool-modern",
  "diagramStyle": "handDrawn"
} as const;

export const presets_starry = {
  "id": "starry",
  "name": "星空梦幻",
  "name_en": "Starry",
  "description": "蓝紫梦幻，童趣星空风格",
  "description_en": "Blue-purple dreamy starry style",
  "author": "Theme System",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Century Gothic"
    },
    "headings": {},
    "code": {
      "fontFamily": "Consolas"
    }
  },
  "layoutScheme": "student",
  "colorScheme": "starry",
  "tableStyle": "minimal-gray",
  "codeTheme": "cool-modern",
  "diagramStyle": "handDrawn"
} as const;

export const presets_sunset = {
  "id": "sunset",
  "name": "日落暖阳",
  "name_en": "Sunset Warm",
  "description": "橙黄色系，温暖舒适的日落风格",
  "description_en": "Orange-yellow for warm and cozy sunset style",
  "author": "Theme System",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Georgia"
    },
    "headings": {},
    "code": {
      "fontFamily": "Consolas"
    }
  },
  "layoutScheme": "book",
  "colorScheme": "sunset",
  "tableStyle": "minimal-gray",
  "codeTheme": "warm-book"
} as const;

export const presets_swiss = {
  "id": "swiss",
  "name": "瑞士极简",
  "name_en": "Swiss Minimal",
  "description": "Helvetica 风格，网格系统，极致简洁",
  "description_en": "Helvetica style with grid system, ultimate simplicity",
  "author": "Theme System",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Helvetica Neue"
    },
    "headings": {},
    "code": {
      "fontFamily": "Monaco"
    }
  },
  "layoutScheme": "document",
  "colorScheme": "neutral",
  "tableStyle": "borderless",
  "codeTheme": "light-clean"
} as const;

export const presets_technical = {
  "id": "technical",
  "name": "技术文档",
  "name_en": "Technical",
  "description": "专为技术文档设计，清晰简洁的极简风格",
  "description_en": "Designed for technical documentation with clean minimalist style",
  "author": "Markdown Viewer Extension",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Arial"
    },
    "headings": {},
    "code": {
      "fontFamily": "Monaco"
    }
  },
  "layoutScheme": "technical",
  "colorScheme": "cool",
  "tableStyle": "modern-tech",
  "codeTheme": "cool-modern"
} as const;

export const presets_typewriter = {
  "id": "typewriter",
  "name": "复古打字",
  "name_en": "Typewriter",
  "description": "Courier New 字体，复古打字机风格",
  "description_en": "Courier New font with retro typewriter style",
  "author": "Markdown Viewer Extension",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Courier New"
    },
    "headings": {},
    "code": {
      "fontFamily": "Courier New"
    }
  },
  "layoutScheme": "book",
  "colorScheme": "sepia",
  "tableStyle": "borderless",
  "codeTheme": "warm-book",
  "diagramStyle": "handDrawn"
} as const;

export const presets_verdana = {
  "id": "verdana",
  "name": "网页显示",
  "name_en": "Web Display",
  "description": "Verdana 字体，屏幕显示清晰锐利",
  "description_en": "Verdana font with clear and sharp screen display",
  "author": "Markdown Viewer Extension",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "Verdana"
    },
    "headings": {},
    "code": {
      "fontFamily": "Monaco"
    }
  },
  "layoutScheme": "document",
  "colorScheme": "cool",
  "tableStyle": "grid",
  "codeTheme": "cool-modern"
} as const;

export const presets_water = {
  "id": "water",
  "name": "水墨诗意",
  "name_en": "Ink Poetry",
  "description": "仿宋字体，中国传统水墨美学",
  "description_en": "FangSong font with traditional Chinese ink aesthetics",
  "author": "Markdown Viewer Extension",
  "version": "1.0.0",
  "fontScheme": {
    "body": {
      "fontFamily": "FangSong"
    },
    "headings": {},
    "code": {
      "fontFamily": "Courier New"
    }
  },
  "layoutScheme": "book",
  "colorScheme": "sepia",
  "tableStyle": "borderless",
  "codeTheme": "warm-book"
} as const;

export const code_themes_business_contrast = {
  "id": "business-contrast",
  "name": "商务对比",
  "description": "高对比度配色，适合演示和商务",
  "description_en": "Business contrast colors for presentation",
  
  "foreground": "#000000",
  "colors": {
    "keyword": "#0000ff",
    "built_in": "#0000ff",
    "literal": "#a31515",
    "number": "#a31515",
    "string": "#a31515",
    "title": "#a31515",
    "attr": "#ff0000",
    "comment": "#008000",
    "meta": "#2b91af",
    "params": "#000000",
    "symbol": "#00b0e8",
    "type": "#a31515",
    "addition": "#a31515",
    "deletion": "#2b91af",
    "quote": "#008000",
    "regexp": "#a31515",
    "selector_tag": "#0000ff",
    "selector_id": "#000000",
    "selector_class": "#000000",
    "variable": "#008000",
    "property": "#000000"
  }
} as const;

export const code_themes_colorful = {
  "id": "colorful",
  "name": "多彩活力",
  "description": "多彩配色方案，活力友好",
  "description_en": "Colorful scheme, vibrant and friendly",
  
  "foreground": "#383a42",
  "colors": {
    "keyword": "#a626a4",
    "built_in": "#c18401",
    "literal": "#0184bb",
    "number": "#986801",
    "operator": "#383a42",
    "string": "#50a14f",
    "title": "#4078f2",
    "attr": "#986801",
    "comment": "#a0a1a7",
    "meta": "#4078f2",
    "params": "#383a42",
    "symbol": "#e45649",
    "type": "#c18401",
    "addition": "#50a14f",
    "deletion": "#e45649",
    "quote": "#a0a1a7",
    "regexp": "#50a14f",
    "selector_tag": "#e45649",
    "selector_id": "#4078f2",
    "selector_class": "#c18401",
    "variable": "#e45649",
    "property": "#4078f2"
  }
} as const;

export const code_themes_cool_modern = {
  "id": "cool-modern",
  "name": "冷色现代",
  "description": "现代冷色调配色，专业简洁",
  "description_en": "Modern cool-toned colors, professional and clean",
  
  "foreground": "#263238",
  "colors": {
    "keyword": "#0277bd",
    "built_in": "#00838f",
    "literal": "#00897b",
    "number": "#f57c00",
    "string": "#00897b",
    "title": "#1976d2",
    "attr": "#00838f",
    "comment": "#90a4ae",
    "meta": "#5e35b1",
    "params": "#263238",
    "symbol": "#d32f2f",
    "type": "#00838f",
    "addition": "#388e3c",
    "deletion": "#d32f2f",
    "quote": "#90a4ae",
    "regexp": "#00897b",
    "selector_tag": "#0277bd",
    "selector_id": "#1976d2",
    "selector_class": "#00838f",
    "variable": "#5e35b1",
    "property": "#1976d2"
  }
} as const;

export const code_themes_high_contrast = {
  "id": "business-contrast",
  "name": "商务对比",
  "description": "高对比度配色，适合演示和商务",
  "description_en": "Business contrast colors for presentation",
  
  "foreground": "#000000",
  "colors": {
    "keyword": "#0000ff",
    "built_in": "#0000ff",
    "literal": "#a31515",
    "number": "#a31515",
    "string": "#a31515",
    "title": "#a31515",
    "attr": "#ff0000",
    "comment": "#008000",
    "meta": "#2b91af",
    "params": "#000000",
    "symbol": "#00b0e8",
    "type": "#a31515",
    "addition": "#a31515",
    "deletion": "#2b91af",
    "quote": "#008000",
    "regexp": "#a31515",
    "selector_tag": "#0000ff",
    "selector_id": "#000000",
    "selector_class": "#000000",
    "variable": "#008000",
    "property": "#000000"
  }
} as const;

export const code_themes_light_clean = {
  "id": "light-clean",
  "name": "清爽亮色",
  "description": "清爽的浅色配色方案，适合日常使用",
  "description_en": "Clean light color scheme for daily use",
  
  "foreground": "#24292e",
  "colors": {
    "keyword": "#d73a49",
    "built_in": "#e36209",
    "literal": "#005cc5",
    "number": "#005cc5",
    "string": "#032f62",
    "title": "#6f42c1",
    "attr": "#005cc5",
    "comment": "#6a737d",
    "meta": "#005cc5",
    "params": "#24292e",
    "symbol": "#e36209",
    "type": "#d73a49",
    "addition": "#22863a",
    "deletion": "#b31d28",
    "quote": "#22863a",
    "regexp": "#032f62",
    "selector_tag": "#22863a",
    "selector_id": "#005cc5",
    "selector_class": "#005cc5",
    "variable": "#e36209",
    "property": "#005cc5"
  }
} as const;

export const code_themes_warm_book = {
  "id": "warm-book",
  "name": "温暖书卷",
  "description": "温暖的书籍风格配色，适合长文阅读",
  "description_en": "Warm book-style colors for long reading",
  
  "foreground": "#657b83",
  "colors": {
    "keyword": "#859900",
    "built_in": "#b58900",
    "literal": "#2aa198",
    "number": "#2aa198",
    "string": "#2aa198",
    "title": "#268bd2",
    "attr": "#b58900",
    "comment": "#93a1a1",
    "meta": "#859900",
    "params": "#657b83",
    "symbol": "#cb4b16",
    "type": "#b58900",
    "addition": "#859900",
    "deletion": "#dc322f",
    "quote": "#93a1a1",
    "regexp": "#dc322f",
    "selector_tag": "#268bd2",
    "selector_id": "#268bd2",
    "selector_class": "#268bd2",
    "variable": "#268bd2",
    "property": "#268bd2"
  }
} as const;

export const color_schemes_candy = {
  "id": "candy",
  "name": "糖果甜心",
  "name_en": "Candy",
  "description": "粉橙色系，甜美可爱的糖果风格",
  "description_en": "Pink-orange scheme for sweet and adorable candy styles",
  
  "text": {
    "primary": "#881337",
    "secondary": "#9f1239",
    "muted": "#be123c"
  },
  
  "accent": {
    "link": "#e11d48",
    "linkHover": "#be123c"
  },
  
  "background": {
    "code": "#fff1f2"
  },
  
  "blockquote": {
    "border": "#fda4af"
  },
  
  "table": {
    "border": "#fda4af",
    "headerBackground": "#fecdd3",
    "headerText": "#881337",
    "zebraEven": "#fff1f2",
    "zebraOdd": "#fff7ed"
  }
} as const;

export const color_schemes_cool = {
  "id": "cool",
  "name": "冷色调",
  "name_en": "Cool",
  "description": "清爽的蓝色系，适合技术和科技风格",
  "description_en": "Cool blue scheme for technical and modern styles",
  
  "text": {
    "primary": "#0f172a",
    "secondary": "#334155",
    "muted": "#64748b"
  },
  
  "accent": {
    "link": "#0077b6",
    "linkHover": "#005f92"
  },
  
  "background": {
    "code": "#f0f9ff"
  },
  
  "blockquote": {
    "border": "#7dd3fc"
  },
  
  "table": {
    "border": "#7dd3fc",
    "headerBackground": "#e0f2fe",
    "headerText": "#0c4a6e",
    "zebraEven": "#f0f9ff",
    "zebraOdd": "#ffffff"
  }
} as const;

export const color_schemes_coral = {
  "id": "coral",
  "name": "珊瑚活力",
  "name_en": "Coral",
  "description": "温暖橙粉色系，友好亲和的活力风格",
  "description_en": "Warm coral-pink scheme for friendly and vibrant styles",
  
  "text": {
    "primary": "#450a0a",
    "secondary": "#7f1d1d",
    "muted": "#b91c1c"
  },
  
  "accent": {
    "link": "#dc2626",
    "linkHover": "#b91c1c"
  },
  
  "background": {
    "code": "#fef2f2"
  },
  
  "blockquote": {
    "border": "#fca5a5"
  },
  
  "table": {
    "border": "#fca5a5",
    "headerBackground": "#fecaca",
    "headerText": "#450a0a",
    "zebraEven": "#fff5f5",
    "zebraOdd": "#fffbeb"
  }
} as const;

export const color_schemes_dino = {
  "id": "dino",
  "name": "恐龙探险",
  "name_en": "Dinosaur",
  "description": "绿橙色系，活力探索的恐龙风格",
  "description_en": "Green-orange scheme for adventurous dinosaur styles",
  
  "text": {
    "primary": "#365314",
    "secondary": "#3f6212",
    "muted": "#65a30d"
  },
  
  "accent": {
    "link": "#4d7c0f",
    "linkHover": "#3f6212"
  },
  
  "background": {
    "code": "#f7fee7"
  },
  
  "blockquote": {
    "border": "#a3e635"
  },
  
  "table": {
    "border": "#a3e635",
    "headerBackground": "#bef264",
    "headerText": "#365314",
    "zebraEven": "#f7fee7",
    "zebraOdd": "#fff7ed"
  }
} as const;

export const color_schemes_forest = {
  "id": "forest",
  "name": "森林自然",
  "name_en": "Forest",
  "description": "绿色系，自然环保的森林风格",
  "description_en": "Green scheme for natural and eco-friendly forest styles",
  
  "text": {
    "primary": "#14532d",
    "secondary": "#166534",
    "muted": "#4d7c0f"
  },
  
  "accent": {
    "link": "#15803d",
    "linkHover": "#166534"
  },
  
  "background": {
    "code": "#f0fdf4"
  },
  
  "blockquote": {
    "border": "#4ade80"
  },
  
  "table": {
    "border": "#4ade80",
    "headerBackground": "#bbf7d0",
    "headerText": "#14532d",
    "zebraEven": "#f0fdf4",
    "zebraOdd": "#fefce8"
  }
} as const;

export const color_schemes_garden = {
  "id": "garden",
  "name": "花园清新",
  "name_en": "Garden",
  "description": "粉绿色系，清新可爱的花园风格",
  "description_en": "Pink-green scheme for fresh and lovely garden styles",
  
  "text": {
    "primary": "#701a75",
    "secondary": "#86198f",
    "muted": "#a21caf"
  },
  
  "accent": {
    "link": "#047857",
    "linkHover": "#065f46"
  },
  
  "background": {
    "code": "#fdf2f8"
  },
  
  "blockquote": {
    "border": "#4ade80"
  },
  
  "table": {
    "border": "#4ade80",
    "headerBackground": "#dcfce7",
    "headerText": "#166534",
    "zebraEven": "#f0fdf4",
    "zebraOdd": "#fefce8"
  }
} as const;

export const color_schemes_neutral = {
  "id": "neutral",
  "name": "中性色",
  "name_en": "Neutral",
  "description": "经典黑白灰配色，适合大多数文档",
  "description_en": "Classic black/white/gray scheme for most documents",
  
  "text": {
    "primary": "#171717",
    "secondary": "#404040",
    "muted": "#737373"
  },
  
  "accent": {
    "link": "#0369a1",
    "linkHover": "#0c4a6e"
  },
  
  "background": {
    "code": "#f5f5f5"
  },
  
  "blockquote": {
    "border": "#a3a3a3"
  },
  
  "table": {
    "border": "#a3a3a3",
    "headerBackground": "#e5e5e5",
    "headerText": "#171717",
    "zebraEven": "#fafafa",
    "zebraOdd": "#ffffff"
  }
} as const;

export const color_schemes_ocean = {
  "id": "ocean",
  "name": "海洋清新",
  "name_en": "Ocean",
  "description": "蓝绿色系，清爽自然的海洋风格",
  "description_en": "Blue-green scheme for fresh and natural ocean styles",
  
  "text": {
    "primary": "#164e63",
    "secondary": "#155e75",
    "muted": "#0e7490"
  },
  
  "accent": {
    "link": "#0e7490",
    "linkHover": "#155e75"
  },
  
  "background": {
    "code": "#ecfeff"
  },
  
  "blockquote": {
    "border": "#22d3ee"
  },
  
  "table": {
    "border": "#22d3ee",
    "headerBackground": "#a5f3fc",
    "headerText": "#164e63",
    "zebraEven": "#ecfeff",
    "zebraOdd": "#f0fdfa"
  }
} as const;

export const color_schemes_rainbow = {
  "id": "rainbow",
  "name": "彩虹多彩",
  "name_en": "Rainbow",
  "description": "各级标题不同颜色，活泼童趣的多彩风格",
  "description_en": "Multi-colored headings for vibrant and playful styles",
  
  "text": {
    "primary": "#1e1b4b",
    "secondary": "#3730a3",
    "muted": "#6366f1"
  },
  
  "accent": {
    "link": "#7c3aed",
    "linkHover": "#6d28d9"
  },
  
  "background": {
    "code": "#eef2ff"
  },
  
  "blockquote": {
    "border": "#a5b4fc"
  },
  
  "table": {
    "border": "#a5b4fc",
    "headerBackground": "#e0e7ff",
    "headerText": "#1e1b4b",
    "zebraEven": "#faf5ff",
    "zebraOdd": "#ffffff"
  },
  
  "headings": {
    "h1": "#ef4444",
    "h2": "#f97316",
    "h3": "#eab308",
    "h4": "#22c55e",
    "h5": "#3b82f6",
    "h6": "#8b5cf6"
  }
} as const;

export const color_schemes_sakura = {
  "id": "sakura",
  "name": "樱花粉",
  "name_en": "Sakura",
  "description": "柔和的粉色系，适合温柔优雅的风格",
  "description_en": "Soft pink scheme for gentle and elegant styles",
  
  "text": {
    "primary": "#831843",
    "secondary": "#9d174d",
    "muted": "#be185d"
  },
  
  "accent": {
    "link": "#db2777",
    "linkHover": "#be185d"
  },
  
  "background": {
    "code": "#fdf2f8"
  },
  
  "blockquote": {
    "border": "#f9a8d4"
  },
  
  "table": {
    "border": "#f9a8d4",
    "headerBackground": "#fce7f3",
    "headerText": "#831843",
    "zebraEven": "#fdf2f8",
    "zebraOdd": "#fffbfc"
  }
} as const;

export const color_schemes_sepia = {
  "id": "sepia",
  "name": "复古棕",
  "name_en": "Sepia",
  "description": "怀旧的泛黄色调，适合打字机和手稿风格",
  "description_en": "Nostalgic sepia tones for typewriter and manuscript styles",
  
  "text": {
    "primary": "#292524",
    "secondary": "#57534e",
    "muted": "#78716c"
  },
  
  "accent": {
    "link": "#a16207",
    "linkHover": "#854d0e"
  },
  
  "background": {
    "code": "#faf5ef"
  },
  
  "blockquote": {
    "border": "#a8a29e"
  },
  
  "table": {
    "border": "#a8a29e",
    "headerBackground": "#f5f0e6",
    "headerText": "#292524",
    "zebraEven": "#faf5ef",
    "zebraOdd": "#fcf9f3"
  }
} as const;

export const color_schemes_space = {
  "id": "space",
  "name": "太空探索",
  "name_en": "Space",
  "description": "蓝橙色系，科幻好奇的太空风格",
  "description_en": "Blue-orange scheme for sci-fi space exploration styles",
  
  "text": {
    "primary": "#1e3a8a",
    "secondary": "#1e40af",
    "muted": "#3b82f6"
  },
  
  "accent": {
    "link": "#4f46e5",
    "linkHover": "#4338ca"
  },
  
  "background": {
    "code": "#eff6ff"
  },
  
  "blockquote": {
    "border": "#93c5fd"
  },
  
  "table": {
    "border": "#93c5fd",
    "headerBackground": "#bfdbfe",
    "headerText": "#1e3a8a",
    "zebraEven": "#eff6ff",
    "zebraOdd": "#fff7ed"
  }
} as const;

export const color_schemes_starry = {
  "id": "starry",
  "name": "星空梦幻",
  "name_en": "Starry",
  "description": "蓝紫色系，梦幻童趣的星空风格",
  "description_en": "Blue-purple scheme for dreamy starry styles",
  
  "text": {
    "primary": "#4c1d95",
    "secondary": "#5b21b6",
    "muted": "#7c3aed"
  },
  
  "accent": {
    "link": "#a21caf",
    "linkHover": "#86198f"
  },
  
  "background": {
    "code": "#eef2ff"
  },
  
  "blockquote": {
    "border": "#a5b4fc"
  },
  
  "table": {
    "border": "#a5b4fc",
    "headerBackground": "#c7d2fe",
    "headerText": "#1e1b4b",
    "zebraEven": "#f5f3ff",
    "zebraOdd": "#faf5ff"
  }
} as const;

export const color_schemes_sunset = {
  "id": "sunset",
  "name": "日落暖阳",
  "name_en": "Sunset",
  "description": "橙黄色系，温暖舒适的日落风格",
  "description_en": "Orange-yellow scheme for warm and cozy sunset styles",
  
  "text": {
    "primary": "#431407",
    "secondary": "#7c2d12",
    "muted": "#c2410c"
  },
  
  "accent": {
    "link": "#c2410c",
    "linkHover": "#9a3412"
  },
  
  "background": {
    "code": "#fff7ed"
  },
  
  "blockquote": {
    "border": "#fdba74"
  },
  
  "table": {
    "border": "#fdba74",
    "headerBackground": "#fed7aa",
    "headerText": "#431407",
    "zebraEven": "#fff7ed",
    "zebraOdd": "#fffbeb"
  }
} as const;

export const color_schemes_warm = {
  "id": "warm",
  "name": "暖色调",
  "name_en": "Warm",
  "description": "温暖的棕橙色系，适合文艺和手写风格",
  "description_en": "Warm brown-orange scheme for literary and handwritten styles",
  
  "text": {
    "primary": "#1c1917",
    "secondary": "#44403c",
    "muted": "#78716c"
  },
  
  "accent": {
    "link": "#b45309",
    "linkHover": "#92400e"
  },
  
  "background": {
    "code": "#faf5f0"
  },
  
  "blockquote": {
    "border": "#a8a29e"
  },
  
  "table": {
    "border": "#a8a29e",
    "headerBackground": "#fef3e2",
    "headerText": "#1c1917",
    "zebraEven": "#fffbf5",
    "zebraOdd": "#fffcf7"
  }
} as const;

export const layout_schemes_academic = {
  "id": "academic",
  "name": "学术论文",
  "name_en": "Academic",
  "description": "层级平缓的布局，适合学术论文和正式文档",
  "description_en": "Gradual hierarchy layout for academic papers and formal documents",
  
  "body": {
    "fontSize": "12pt",
    "lineHeight": 1.75
  },
  
  "headings": {
    "h1": { "fontSize": "18pt", "spacingBefore": "0pt", "spacingAfter": "16pt" },
    "h2": { "fontSize": "16pt", "spacingBefore": "16pt", "spacingAfter": "10pt" },
    "h3": { "fontSize": "14pt", "spacingBefore": "14pt", "spacingAfter": "8pt" },
    "h4": { "fontSize": "13pt", "spacingBefore": "12pt", "spacingAfter": "6pt" },
    "h5": { "fontSize": "12pt", "spacingBefore": "10pt", "spacingAfter": "5pt" },
    "h6": { "fontSize": "12pt", "spacingBefore": "8pt", "spacingAfter": "4pt" }
  },
  
  "code": {
    "fontSize": "10pt"
  },
  
  "blocks": {
    "paragraph": { "spacingAfter": "10pt" },
    "list": { "spacingAfter": "13pt" },
    "listItem": { "spacingAfter": "3pt" },
    "blockquote": { 
      "spacingBefore": "10pt",
      "spacingAfter": "10pt",
      "paddingVertical": "1pt",
      "paddingHorizontal": "13pt"
    },
    "codeBlock": { "spacingAfter": "12pt" },
    "table": { "spacingAfter": "12pt" },
    "horizontalRule": { "spacingBefore": "20pt", "spacingAfter": "20pt" }
  }
} as const;

export const layout_schemes_book = {
  "id": "book",
  "name": "书籍排版",
  "name_en": "Book",
  "description": "舒适阅读的布局，适合长文档和书籍",
  "description_en": "Comfortable reading layout for long documents and books",
  
  "body": {
    "fontSize": "12pt",
    "lineHeight": 1.6
  },
  
  "headings": {
    "h1": { "fontSize": "22pt", "spacingBefore": "0pt", "spacingAfter": "14pt" },
    "h2": { "fontSize": "18pt", "spacingBefore": "18pt", "spacingAfter": "10pt" },
    "h3": { "fontSize": "16pt", "spacingBefore": "16pt", "spacingAfter": "8pt" },
    "h4": { "fontSize": "14pt", "spacingBefore": "14pt", "spacingAfter": "7pt" },
    "h5": { "fontSize": "13pt", "spacingBefore": "12pt", "spacingAfter": "6pt" },
    "h6": { "fontSize": "12pt", "spacingBefore": "10pt", "spacingAfter": "5pt" }
  },
  
  "code": {
    "fontSize": "10pt"
  },
  
  "blocks": {
    "paragraph": { "spacingAfter": "12pt" },
    "list": { "spacingAfter": "14pt" },
    "listItem": { "spacingAfter": "4pt" },
    "blockquote": { 
      "spacingBefore": "12pt",
      "spacingAfter": "12pt",
      "paddingVertical": "2pt",
      "paddingHorizontal": "15pt"
    },
    "codeBlock": { "spacingAfter": "14pt" },
    "table": { "spacingAfter": "14pt" },
    "horizontalRule": { "spacingBefore": "24pt", "spacingAfter": "24pt" }
  }
} as const;

export const layout_schemes_document = {
  "id": "document",
  "name": "通用文档",
  "name_en": "Document",
  "description": "平衡适中的布局，适合日常文档",
  "description_en": "Balanced layout for everyday documents",
  
  "body": {
    "fontSize": "12pt",
    "lineHeight": 1.5
  },
  
  "headings": {
    "h1": { "fontSize": "22pt", "spacingBefore": "0pt", "spacingAfter": "12pt", "alignment": "center" },
    "h2": { "fontSize": "18pt", "spacingBefore": "16pt", "spacingAfter": "8pt" },
    "h3": { "fontSize": "16pt", "spacingBefore": "14pt", "spacingAfter": "7pt" },
    "h4": { "fontSize": "14pt", "spacingBefore": "12pt", "spacingAfter": "6pt" },
    "h5": { "fontSize": "13pt", "spacingBefore": "10pt", "spacingAfter": "5pt" },
    "h6": { "fontSize": "12pt", "spacingBefore": "8pt", "spacingAfter": "4pt" }
  },
  
  "code": {
    "fontSize": "10pt"
  },
  
  "blocks": {
    "paragraph": { "spacingAfter": "10pt" },
    "list": { "spacingAfter": "13pt" },
    "listItem": { "spacingAfter": "3pt" },
    "blockquote": { 
      "spacingBefore": "10pt",
      "spacingAfter": "10pt",
      "paddingVertical": "1pt",
      "paddingHorizontal": "13pt"
    },
    "codeBlock": { "spacingAfter": "12pt" },
    "table": { "spacingAfter": "12pt" },
    "horizontalRule": { "spacingBefore": "20pt", "spacingAfter": "20pt" }
  }
} as const;

export const layout_schemes_magazine = {
  "id": "magazine",
  "name": "杂志风格",
  "name_en": "Magazine",
  "description": "大标题差异的布局，适合杂志和创意文档",
  "description_en": "Large heading contrast layout for magazines and creative documents",
  
  "body": {
    "fontSize": "12pt",
    "lineHeight": 1.5
  },
  
  "headings": {
    "h1": { "fontSize": "28pt", "spacingBefore": "0pt", "spacingAfter": "16pt" },
    "h2": { "fontSize": "22pt", "spacingBefore": "20pt", "spacingAfter": "10pt" },
    "h3": { "fontSize": "18pt", "spacingBefore": "16pt", "spacingAfter": "8pt" },
    "h4": { "fontSize": "15pt", "spacingBefore": "14pt", "spacingAfter": "7pt" },
    "h5": { "fontSize": "13pt", "spacingBefore": "12pt", "spacingAfter": "6pt" },
    "h6": { "fontSize": "12pt", "spacingBefore": "10pt", "spacingAfter": "5pt" }
  },
  
  "code": {
    "fontSize": "10pt"
  },
  
  "blocks": {
    "paragraph": { "spacingAfter": "10pt" },
    "list": { "spacingAfter": "13pt" },
    "listItem": { "spacingAfter": "3pt" },
    "blockquote": { 
      "spacingBefore": "12pt",
      "spacingAfter": "12pt",
      "paddingVertical": "2pt",
      "paddingHorizontal": "16pt"
    },
    "codeBlock": { "spacingAfter": "12pt" },
    "table": { "spacingAfter": "12pt" },
    "horizontalRule": { "spacingBefore": "20pt", "spacingAfter": "20pt" }
  }
} as const;

export const layout_schemes_student = {
  "id": "student",
  "name": "学生文档",
  "name_en": "Student",
  "description": "大字号大行距，适合学生作文和笔记",
  "description_en": "Large font and spacing for student essays and notes",
  
  "body": {
    "fontSize": "14pt",
    "lineHeight": 1.8
  },
  
  "headings": {
    "h1": { "fontSize": "24pt", "spacingBefore": "0pt", "spacingAfter": "16pt" },
    "h2": { "fontSize": "20pt", "spacingBefore": "20pt", "spacingAfter": "12pt" },
    "h3": { "fontSize": "18pt", "spacingBefore": "18pt", "spacingAfter": "10pt" },
    "h4": { "fontSize": "16pt", "spacingBefore": "16pt", "spacingAfter": "8pt" },
    "h5": { "fontSize": "15pt", "spacingBefore": "14pt", "spacingAfter": "7pt" },
    "h6": { "fontSize": "14pt", "spacingBefore": "12pt", "spacingAfter": "6pt" }
  },
  
  "code": {
    "fontSize": "12pt"
  },
  
  "blocks": {
    "paragraph": { "spacingAfter": "14pt" },
    "list": { "spacingAfter": "16pt" },
    "listItem": { "spacingAfter": "6pt" },
    "blockquote": { 
      "spacingBefore": "14pt",
      "spacingAfter": "14pt",
      "paddingVertical": "4pt",
      "paddingHorizontal": "18pt"
    },
    "codeBlock": { "spacingAfter": "16pt" },
    "table": { "spacingAfter": "16pt" },
    "horizontalRule": { "spacingBefore": "28pt", "spacingAfter": "28pt" }
  }
} as const;

export const layout_schemes_technical = {
  "id": "technical",
  "name": "技术文档",
  "name_en": "Technical",
  "description": "紧凑高效的布局，适合技术文档和API文档",
  "description_en": "Compact and efficient layout for technical and API documentation",
  
  "body": {
    "fontSize": "11pt",
    "lineHeight": 1.4
  },
  
  "headings": {
    "h1": { "fontSize": "18pt", "spacingBefore": "0pt", "spacingAfter": "10pt" },
    "h2": { "fontSize": "15pt", "spacingBefore": "14pt", "spacingAfter": "7pt" },
    "h3": { "fontSize": "13pt", "spacingBefore": "12pt", "spacingAfter": "6pt" },
    "h4": { "fontSize": "12pt", "spacingBefore": "10pt", "spacingAfter": "5pt" },
    "h5": { "fontSize": "11pt", "spacingBefore": "8pt", "spacingAfter": "4pt" },
    "h6": { "fontSize": "11pt", "spacingBefore": "6pt", "spacingAfter": "3pt" }
  },
  
  "code": {
    "fontSize": "10pt"
  },
  
  "blocks": {
    "paragraph": { "spacingAfter": "8pt" },
    "list": { "spacingAfter": "10pt" },
    "listItem": { "spacingAfter": "2pt" },
    "blockquote": { 
      "spacingBefore": "8pt",
      "spacingAfter": "8pt",
      "paddingVertical": "1pt",
      "paddingHorizontal": "12pt"
    },
    "codeBlock": { "spacingAfter": "10pt" },
    "table": { "spacingAfter": "10pt" },
    "horizontalRule": { "spacingBefore": "16pt", "spacingAfter": "16pt" }
  }
} as const;

export const table_styles_academic = {
  "id": "academic",
  "name": "学术风格",
  "name_en": "Academic",
  "description": "双线表头 + 单线分隔，适合论文和学术文档",
  "description_en": "Double-line header + single-line separators, ideal for papers and academic documents",
  "border": {
    "headerTop": {
      "width": "1.5pt",
      "style": "double"
    },
    "headerBottom": {
      "width": "1.5pt",
      "style": "single"
    },
    "lastRowBottom": {
      "width": "1.5pt",
      "style": "single"
    }
  },
  "header": {
    "fontWeight": "bold"
  },
  "cell": {
    "padding": "6pt"
  },
  "zebra": {
    "enabled": false
  }
} as const;

export const table_styles_borderless = {
  "id": "borderless",
  "name": "无边框",
  "name_en": "Borderless",
  "description": "仅表头有下边框",
  "description_en": "Only header has bottom border",
  "border": {
    "headerBottom": {
      "width": "2pt",
      "style": "single"
    },
    "lastRowBottom": {
      "width": "1pt",
      "style": "single"
    }
  },
  "header": {
    "fontWeight": "bold"
  },
  "cell": {
    "padding": "8pt"
  },
  "zebra": {
    "enabled": false
  }
} as const;

export const table_styles_compact = {
  "id": "compact",
  "name": "紧凑型",
  "name_en": "Compact",
  "description": "小间距 + 细边框，适合数据密集型表格",
  "description_en": "Small padding + thin borders, ideal for data-heavy tables",
  "border": {
    "all": {
      "width": "0.5pt",
      "style": "single"
    }
  },
  "header": {
    "fontWeight": "bold",
    "fontSize": "10pt"
  },
  "cell": {
    "padding": "4pt",
    "fontSize": "10pt"
  },
  "zebra": {
    "enabled": true
  }
} as const;

export const table_styles_grid = {
  "id": "grid",
  "name": "网格样式",
  "name_en": "Grid Style",
  "description": "完整边框，表头浅灰背景，斑马纹",
  "description_en": "Full borders, light gray header, zebra stripes",
  "border": {
    "all": {
      "width": "1pt",
      "style": "single"
    }
  },
  "header": {
    "fontWeight": "bold"
  },
  "cell": {
    "padding": "8pt"
  },
  "zebra": {
    "enabled": true
  }
} as const;

export const table_styles_high_contrast = {
  "id": "high-contrast",
  "name": "高对比度",
  "name_en": "High Contrast",
  "description": "黑白高对比 + 粗边框，适合打印和可访问性需求",
  "description_en": "Black & white high contrast with thick borders, ideal for printing and accessibility",
  "border": {
    "all": {
      "width": "2pt",
      "style": "single"
    }
  },
  "header": {
    "fontWeight": "bold"
  },
  "cell": {
    "padding": "8pt"
  },
  "zebra": {
    "enabled": true
  }
} as const;

export const table_styles_minimal_gray = {
  "id": "minimal-gray",
  "name": "极简灰调",
  "name_en": "Minimal Gray",
  "description": "仅横向边框 + 灰色调 + 简洁美观",
  "description_en": "Horizontal borders only + gray tones + clean look",
  "border": {
    "headerBottom": {
      "width": "1.5pt",
      "style": "single"
    },
    "rowBottom": {
      "width": "1pt",
      "style": "single"
    }
  },
  "header": {
    "fontWeight": "bold"
  },
  "cell": {
    "padding": "8pt"
  },
  "zebra": {
    "enabled": false
  }
} as const;

export const table_styles_modern_tech = {
  "id": "modern-tech",
  "name": "现代科技",
  "name_en": "Modern Tech",
  "description": "蓝色主题 + 圆角边框，适合技术文档和产品说明",
  "description_en": "Blue theme with rounded borders, ideal for tech docs and product guides",
  "border": {
    "headerTop": {
      "width": "2pt",
      "style": "single"
    },
    "headerBottom": {
      "width": "2pt",
      "style": "single"
    },
    "rowBottom": {
      "width": "1pt",
      "style": "single"
    },
    "lastRowBottom": {
      "width": "2pt",
      "style": "single"
    }
  },
  "header": {
    "fontWeight": "bold"
  },
  "cell": {
    "padding": "10pt"
  },
  "zebra": {
    "enabled": false
  }
} as const;

export const table_styles_professional = {
  "id": "professional",
  "name": "专业风格",
  "name_en": "Professional",
  "description": "粗表头边框 + 细分隔线",
  "description_en": "Thick header border + thin separators",
  "border": {
    "headerTop": {
      "width": "2pt",
      "style": "single"
    },
    "headerBottom": {
      "width": "2pt",
      "style": "single"
    },
    "rowBottom": {
      "width": "1pt",
      "style": "single"
    },
    "lastRowBottom": {
      "width": "2pt",
      "style": "single"
    }
  },
  "header": {
    "fontWeight": "bold"
  },
  "cell": {
    "padding": "8pt"
  },
  "zebra": {
    "enabled": false
  }
} as const;

export const table_styles_zebra = {
  "id": "zebra",
  "name": "斑马纹",
  "name_en": "Zebra",
  "description": "奇偶行不同背景色，无边框",
  "description_en": "Alternating row colors, no borders",
  "border": {
    "headerBottom": {
      "width": "1pt",
      "style": "single"
    }
  },
  "header": {
    "fontWeight": "bold"
  },
  "cell": {
    "padding": "8pt"
  },
  "zebra": {
    "enabled": true
  }
} as const;

export const registry = {
  "version": "2.0.0",
  "themes": [
    {
      "id": "default",
      "file": "default.json",
      "category": "classic",
      "featured": true,
      "order": 1
    },
    {
      "id": "academic",
      "file": "academic.json",
      "category": "classic",
      "featured": true,
      "order": 2
    },
    {
      "id": "business",
      "file": "business.json",
      "category": "classic",
      "featured": true,
      "order": 3
    },
    {
      "id": "manuscript",
      "file": "manuscript.json",
      "category": "classic",
      "featured": false,
      "order": 4
    },
    {
      "id": "newspaper",
      "file": "newspaper.json",
      "category": "classic",
      "featured": false,
      "order": 5
    },
    {
      "id": "palatino",
      "file": "palatino.json",
      "category": "reading",
      "featured": true,
      "order": 6
    },
    {
      "id": "garamond",
      "file": "garamond.json",
      "category": "reading",
      "featured": true,
      "order": 7
    },
    {
      "id": "typewriter",
      "file": "typewriter.json",
      "category": "reading",
      "featured": true,
      "order": 8
    },
    {
      "id": "elegant",
      "file": "elegant.json",
      "category": "reading",
      "featured": true,
      "order": 9
    },
    {
      "id": "technical",
      "file": "technical.json",
      "category": "modern",
      "featured": true,
      "order": 10
    },
    {
      "id": "swiss",
      "file": "swiss.json",
      "category": "modern",
      "featured": true,
      "order": 11
    },
    {
      "id": "minimal",
      "file": "minimal.json",
      "category": "modern",
      "featured": true,
      "order": 12
    },
    {
      "id": "magazine",
      "file": "magazine.json",
      "category": "creative",
      "featured": true,
      "order": 13
    },
    {
      "id": "century",
      "file": "century.json",
      "category": "creative",
      "featured": true,
      "order": 14
    },
    {
      "id": "handwritten",
      "file": "handwritten.json",
      "category": "creative",
      "featured": true,
      "order": 15
    },
    {
      "id": "verdana",
      "file": "verdana.json",
      "category": "creative",
      "featured": true,
      "order": 16
    },
    {
      "id": "heiti",
      "file": "heiti.json",
      "category": "chinese",
      "featured": true,
      "order": 17
    },
    {
      "id": "mixed",
      "file": "mixed.json",
      "category": "chinese",
      "featured": false,
      "order": 18
    },
    {
      "id": "water",
      "file": "water.json",
      "category": "chinese",
      "featured": true,
      "order": 19
    },
    {
      "id": "rainbow",
      "file": "rainbow.json",
      "category": "playful",
      "featured": true,
      "order": 20
    },
    {
      "id": "starry",
      "file": "starry.json",
      "category": "playful",
      "featured": true,
      "order": 21
    },
    {
      "id": "candy",
      "file": "candy.json",
      "category": "playful",
      "featured": true,
      "order": 22
    },
    {
      "id": "dinosaur",
      "file": "dinosaur.json",
      "category": "playful",
      "featured": true,
      "order": 23
    },
    {
      "id": "space",
      "file": "space.json",
      "category": "playful",
      "featured": true,
      "order": 24
    },
    {
      "id": "garden",
      "file": "garden.json",
      "category": "playful",
      "featured": true,
      "order": 25
    },
    {
      "id": "forest",
      "file": "forest.json",
      "category": "nature",
      "featured": true,
      "order": 26
    },
    {
      "id": "ocean",
      "file": "ocean.json",
      "category": "nature",
      "featured": true,
      "order": 27
    },
    {
      "id": "coral",
      "file": "coral.json",
      "category": "nature",
      "featured": true,
      "order": 28
    },
    {
      "id": "sunset",
      "file": "sunset.json",
      "category": "nature",
      "featured": true,
      "order": 29
    }
  ],
  "categories": {
    "classic": {
      "name": "经典文档",
      "name_en": "Classic Document",
      "description": "传统正式的文档风格，适合公文、报告、论文",
      "description_en": "Traditional formal styles for official documents, reports, papers",
      "order": 1
    },
    "reading": {
      "name": "书籍阅读",
      "name_en": "Book & Reading",
      "description": "舒适的长文阅读体验，适合小说、杂志、博客",
      "description_en": "Comfortable long-form reading for novels, magazines, blogs",
      "order": 2
    },
    "modern": {
      "name": "现代科技",
      "name_en": "Modern Tech",
      "description": "简洁现代的设计风格，适合技术文档、产品说明",
      "description_en": "Clean modern design for technical docs and products",
      "order": 3
    },
    "creative": {
      "name": "创意表达",
      "name_en": "Creative Expression",
      "description": "富有个性的创意风格，适合博客、设计、创意写作",
      "description_en": "Creative styles for blogs, design, creative writing",
      "order": 4
    },
    "chinese": {
      "name": "中文排版",
      "name_en": "Chinese Typography",
      "description": "专为中文优化的排版风格",
      "description_en": "Typography optimized for Chinese content",
      "order": 5
    },
    "playful": {
      "name": "缤纷童趣",
      "name_en": "Colorful & Playful",
      "description": "活泼多彩的风格，适合学生作业、儿童内容",
      "description_en": "Vibrant playful styles for students and kids",
      "order": 6
    },
    "nature": {
      "name": "自然色彩",
      "name_en": "Nature Colors",
      "description": "取自自然的配色，温暖舒适的视觉体验",
      "description_en": "Nature-inspired colors for warm visual experience",
      "order": 7
    }
  },
  "recommendations": {
    "default": "default",
    "academic": "academic",
    "business": "business",
    "technical": "technical",
    "reading": "garamond",
    "book": "palatino",
    "modern": "swiss",
    "screen": "verdana",
    "creative": "magazine"
  }
} as const;

export const fontConfig = {
  "fonts": {
    "Times New Roman": {
      "name": "Times New Roman",
      "displayName": "Times New Roman",
      "webFallback": "'Times New Roman', Times, Georgia, serif, SimSun, STSong",
      "docx": {
        "ascii": "Times New Roman",
        "eastAsia": "SimSun"
      }
    },
    "Arial": {
      "name": "Arial",
      "displayName": "Arial",
      "webFallback": "Arial, Helvetica, 'Helvetica Neue', sans-serif, SimHei, STHeiti",
      "docx": {
        "ascii": "Arial",
        "eastAsia": "SimHei"
      }
    },
    "Georgia": {
      "name": "Georgia",
      "displayName": "Georgia",
      "webFallback": "Georgia, 'Times New Roman', Times, serif, SimSun, STSong",
      "docx": {
        "ascii": "Georgia",
        "eastAsia": "SimSun"
      }
    },
    "Monaco": {
      "name": "Monaco",
      "displayName": "Monaco",
      "webFallback": "Monaco, 'Courier New', monospace, FangSong, STFangsong, 'Zhuque Fangsong'",
      "docx": {
        "ascii": "Consolas",
        "eastAsia": "FangSong"
      }
    },
    "Courier New": {
      "name": "Courier New",
      "displayName": "Courier New",
      "webFallback": "'Courier New', Courier, Monaco, FangSong, STFangsong, 'Zhuque Fangsong', monospace",
      "docx": {
        "ascii": "Courier New",
        "eastAsia": "FangSong"
      }
    },
    "SimSun": {
      "name": "SimSun",
      "displayName": "宋体 (SimSun)",
      "webFallback": "'Times New Roman', serif, SimSun, STSong",
      "docx": {
        "ascii": "Times New Roman",
        "eastAsia": "SimSun"
      }
    },
    "SimHei": {
      "name": "SimHei",
      "displayName": "黑体 (SimHei)",
      "webFallback": "Arial, sans-serif, SimHei, STHeiti",
      "docx": {
        "ascii": "Arial",
        "eastAsia": "SimHei"
      }
    },
    "FangSong": {
      "name": "FangSong",
      "displayName": "仿宋 (FangSong)",
      "webFallback": "FangSong, STFangsong, 'Zhuque Fangsong', Georgia, 'Times New Roman', serif",
      "docx": {
        "ascii": "Georgia",
        "eastAsia": "FangSong"
      }
    },
    "Palatino": {
      "name": "Palatino",
      "displayName": "Palatino",
      "webFallback": "Palatino, Georgia, 'Times New Roman', serif, STSong, SimSun",
      "docx": {
        "ascii": "Palatino Linotype",
        "eastAsia": "SimSun"
      }
    },
    "Verdana": {
      "name": "Verdana",
      "displayName": "Verdana",
      "webFallback": "Verdana, Geneva, Tahoma, Arial, sans-serif, SimHei",
      "docx": {
        "ascii": "Verdana",
        "eastAsia": "SimHei"
      }
    },
    "Tahoma": {
      "name": "Tahoma",
      "displayName": "Tahoma",
      "webFallback": "Tahoma, Verdana, Arial, sans-serif, SimHei",
      "docx": {
        "ascii": "Tahoma",
        "eastAsia": "SimHei"
      }
    },
    "Trebuchet MS": {
      "name": "Trebuchet MS",
      "displayName": "Trebuchet MS",
      "webFallback": "'Trebuchet MS', Tahoma, Arial, sans-serif, SimHei",
      "docx": {
        "ascii": "Trebuchet MS",
        "eastAsia": "SimHei"
      }
    },
    "Comic Sans MS": {
      "name": "Comic Sans MS",
      "displayName": "Comic Sans MS",
      "webFallback": "'Comic Sans MS', 'Comic Neue', 'Marker Felt', FangSong, STFangsong, 'Zhuque Fangsong'",
      "docx": {
        "ascii": "Comic Sans MS",
        "eastAsia": "FangSong"
      }
    },
    "Impact": {
      "name": "Impact",
      "displayName": "Impact",
      "webFallback": "Impact, 'Arial Black', Arial, sans-serif, SimHei",
      "docx": {
        "ascii": "Impact",
        "eastAsia": "SimHei"
      }
    },
    "Lucida Grande": {
      "name": "Lucida Grande",
      "displayName": "Lucida Grande",
      "webFallback": "'Lucida Grande', Geneva, Verdana, Arial, sans-serif, STHeiti, SimHei",
      "docx": {
        "ascii": "Lucida Sans Unicode",
        "eastAsia": "SimHei"
      }
    },
    "Palatino Linotype": {
      "name": "Palatino Linotype",
      "displayName": "Palatino Linotype",
      "webFallback": "'Palatino Linotype', Palatino, 'Book Antiqua', Georgia, 'Times New Roman', serif, SimSun, STSong",
      "docx": {
        "ascii": "Palatino Linotype",
        "eastAsia": "SimSun"
      }
    },
    "Consolas": {
      "name": "Consolas",
      "displayName": "Consolas",
      "webFallback": "Consolas, Monaco, 'Courier New', monospace, FangSong, STFangsong, 'Zhuque Fangsong'",
      "docx": {
        "ascii": "Consolas",
        "eastAsia": "FangSong"
      }
    },
    "Garamond": {
      "name": "Garamond",
      "displayName": "Garamond",
      "webFallback": "Garamond, 'Times New Roman', Georgia, serif, SimSun, STSong",
      "docx": {
        "ascii": "Garamond",
        "eastAsia": "SimSun"
      }
    },
    "Helvetica Neue": {
      "name": "Helvetica Neue",
      "displayName": "Helvetica Neue",
      "webFallback": "'Helvetica Neue', Helvetica, Arial, sans-serif, SimHei, STHeiti",
      "docx": {
        "ascii": "Arial",
        "eastAsia": "SimHei"
      }
    },
    "Century Gothic": {
      "name": "Century Gothic",
      "displayName": "Century Gothic",
      "webFallback": "'Century Gothic', 'Apple Gothic', Arial, sans-serif, SimHei, STHeiti",
      "docx": {
        "ascii": "Century Gothic",
        "eastAsia": "SimHei"
      }
    }
  }
} as const;
